---
engines:
  csslint:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**/*"
exclude_paths:
- dist/**/*
- node_modules/**/*
- tmp/**/*

